package("nanovg_bgfx")
    set_homepage("https://github.com/DvdBr3o/nanovg_bgfx")
    set_description("The nanovg utilities under bgfx.")
    add_urls("https://github.com/DvdBr3o/nanovg_bgfx.git")
    add_versions("2023.05.01", "4a6ba6a9cd867e8ce11206fdeafefa9916b5501e")
    on_install(function(package)
        import("package.tools.xmake").install(package)
    end)